Fix python binding compilation for Windows
When building using MSVC the CL compiler will
fail with the following error:
	fasttext_pybind.cc(171): error C2065: 'ssize_t': undeclared identifier

It seems like ssize_t is a non-standard posix extension which is not
defined in Windows, I added a typedef to the windows version SSIZE_T to
fix it.